/**
 * Export build-time provider data from the same-version pi packages.
 *
 * UI:
 *   - bundledCatalog.ts — provider metadata only (order, login flags). Tiny, eager.
 *   - catalogModels/<id>.ts — packed models per provider (dynamic import chunks).
 *   - catalogModelLoaders.ts — id → dynamic import() map for Vite code-split.
 *
 * Agent:
 *   - providerCatalog.ts — staticProviders metadata only (no models.json load path).
 *
 * Packed model row (v1):
 *   [id, name|0, flags, contextWindow|0, inputCost|-1, outputCost|-1]
 *   flags: 1=vision, 2=reasoning, 4=toolsUnsupported
 */
import * as fs from "node:fs"
import * as path from "node:path"
import {fileURLToPath} from "node:url"
import {ModelRuntime} from "@earendil-works/pi-coding-agent"

type SlimModel = {
  id: string
  name?: string
  contextWindow?: number
  vision?: boolean
  inputCostPerMTok?: number
  outputCostPerMTok?: number
  reasoning?: boolean
  toolsUnsupported?: boolean
}

type SlimProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
  models: SlimModel[]
}

type SlimCatalog = {
  providerOrder: string[]
  providers: SlimProvider[]
}

type StaticProvider = Omit<SlimProvider, "models">

type PackedModel = [
    id: string,
    name: string | 0,
    flags: number,
    contextWindow: number,
    inputCost: number,
    outputCost: number,
]

const GENERATED_HEADER = `/* eslint-disable */
/* Generated by export-bundled-catalog.ts. Do not edit. */

`

const MFLAG_VISION = 1
const MFLAG_REASONING = 2
const MFLAG_TOOLS_UNSUPPORTED = 4

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v)
}

/** Safe chunk file stem; provider ids today are already [a-z0-9-]. */
function fileSafeId(id: string): string {
    const safe = id.replace(/[^a-zA-Z0-9._-]/g, "_")
    if (!safe || safe === "." || safe === "..") {
        throw new Error(`Unsafe provider id for catalog chunk: ${id}`)
    }
    return safe
}

function slimModel(m: {
  id: string
  name?: string
  reasoning?: boolean
  input?: readonly string[]
  supportsTools?: boolean
  cost?: { input?: number; output?: number }
  contextWindow?: number | null
}): SlimModel {
  const out: SlimModel = { id: String(m.id) }
  const name = m.name != null ? String(m.name) : ""
  if (name && name !== out.id) out.name = name

  if (isFiniteNumber(m.contextWindow) && m.contextWindow > 0) {
    out.contextWindow = m.contextWindow
  }

  if (Array.isArray(m.input) && m.input.includes("image")) {
    out.vision = true
  }

  const costIn = m.cost?.input
  const costOut = m.cost?.output
  if (isFiniteNumber(costIn)) out.inputCostPerMTok = costIn
  if (isFiniteNumber(costOut)) out.outputCostPerMTok = costOut

  if (m.reasoning === true) out.reasoning = true
  if (m.supportsTools === false) out.toolsUnsupported = true
  return out
}

function packModel(m: SlimModel): PackedModel {
    let flags = 0
    if (m.vision) flags |= MFLAG_VISION
    if (m.reasoning) flags |= MFLAG_REASONING
    if (m.toolsUnsupported) flags |= MFLAG_TOOLS_UNSUPPORTED
    return [
        m.id,
        m.name && m.name !== m.id ? m.name : 0,
        flags,
        m.contextWindow && m.contextWindow > 0 ? m.contextWindow : 0,
        m.inputCostPerMTok ?? -1,
        m.outputCostPerMTok ?? -1,
    ]
}

async function buildCatalog(): Promise<SlimCatalog> {
  const runtime = await ModelRuntime.create({ modelsPath: null })
  const providers = runtime.getProviders()
  const providerOrder = providers.map((provider) => provider.id)
  return {
    providerOrder,
    providers: providers.map((provider): SlimProvider => {
      const auth = provider.auth
        const supportsLogin = Boolean(auth.oauth || auth.apiKey?.login)
      return {
        id: provider.id,
          ...(supportsLogin ? {supportsLogin: true} : {}),
        models: provider.getModels().map((model) => slimModel(model)),
      }
    }),
  }
}

function renderUiMeta(catalog: SlimCatalog): string {
    const providers = catalog.providers.map(({id, supportsLogin, loginProviderId}) => {
        const p: StaticProvider = {id}
        if (supportsLogin) p.supportsLogin = true
        if (loginProviderId) p.loginProviderId = loginProviderId
        return p
    })
    const meta = {providerOrder: catalog.providerOrder, providers}
    return `${GENERATED_HEADER}export type GeneratedCatalogProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
}

/** Provider metadata only — models load via catalogModelLoaders. */
export type GeneratedBundledCatalog = {
  providerOrder: string[]
  providers: GeneratedCatalogProvider[]
}

export const bundledCatalog: GeneratedBundledCatalog = ${JSON.stringify(meta)}
`
}

function renderPackedModelsModule(models: PackedModel[]): string {
    return `${GENERATED_HEADER}import type { PackedModel } from "../catalogModelTypes"

export const models: PackedModel[] = ${JSON.stringify(models)}
`
}

function renderModelTypes(): string {
    return `${GENERATED_HEADER}/** Packed model row v1 — expand in settings/catalog.ts */
export type PackedModel = [
  id: string,
  name: string | 0,
  flags: number,
  contextWindow: number,
  inputCost: number,
  outputCost: number,
]
`
}

function renderModelLoaders(providerIds: string[]): string {
    const entries = providerIds.map((id) => {
        const file = fileSafeId(id)
        return `  ${JSON.stringify(id)}: () => import("./catalogModels/${file}.js")`
    })
    return `${GENERATED_HEADER}import type { PackedModel } from "./catalogModelTypes"

export type CatalogModelsModule = { models: PackedModel[] }

/** Vite code-splits each import(); call only for connected providers. */
export const catalogModelLoaders: Record<
  string,
  () => Promise<CatalogModelsModule>
> = {
${entries.join(",\n")}
}
`
}

function renderAgentProviders(catalog: SlimCatalog): string {
  const providers: StaticProvider[] = catalog.providers.map(
    ({ id, supportsLogin, loginProviderId }) => {
      const provider: StaticProvider = { id }
      if (supportsLogin) provider.supportsLogin = true
      if (loginProviderId) provider.loginProviderId = loginProviderId
      return provider
    },
  )
  return `${GENERATED_HEADER}export type StaticProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
}

export const staticProviders: readonly StaticProvider[] = ${JSON.stringify(providers)}
`
}

function writeGenerated(outPath: string, contents: string): number {
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, contents, "utf8")
  return fs.statSync(outPath).size
}

function rmrf(dir: string): void {
    fs.rmSync(dir, {recursive: true, force: true})
}

async function main(): Promise<void> {
  const here = path.dirname(fileURLToPath(import.meta.url))
  const repoRoot = path.resolve(here, "../../..")
    const uiGenDir = path.join(repoRoot, "packages/vibefly-ui/src/generated")
    const uiMetaPath = path.join(uiGenDir, "bundledCatalog.ts")
    const uiTypesPath = path.join(uiGenDir, "catalogModelTypes.ts")
    const uiLoadersPath = path.join(uiGenDir, "catalogModelLoaders.ts")
    const uiModelsDir = path.join(uiGenDir, "catalogModels")
  const agentOutPath = path.join(
    repoRoot,
    "packages/vibefly-agent/src/generated/providerCatalog.ts",
  )

  const catalog = await buildCatalog()

    rmrf(uiModelsDir)
    fs.mkdirSync(uiModelsDir, {recursive: true})

    let uiBytes = 0
    uiBytes += writeGenerated(uiTypesPath, renderModelTypes())
    uiBytes += writeGenerated(uiMetaPath, renderUiMeta(catalog))

    const providerIds: string[] = []
    const seenFiles = new Set<string>()
    for (const provider of catalog.providers) {
        const file = fileSafeId(provider.id)
        if (seenFiles.has(file)) {
            throw new Error(`Catalog chunk filename collision: ${file}`)
        }
        seenFiles.add(file)
        providerIds.push(provider.id)
        const packed = provider.models.map(packModel)
        uiBytes += writeGenerated(
            path.join(uiModelsDir, `${file}.ts`),
            renderPackedModelsModule(packed),
        )
    }
    uiBytes += writeGenerated(uiLoadersPath, renderModelLoaders(providerIds))

  const agentBytes = writeGenerated(agentOutPath, renderAgentProviders(catalog))
  const modelCount = catalog.providers.reduce((n, p) => n + p.models.length, 0)
  console.error(
    `export-bundled-catalog: ${catalog.providers.length} providers, ` +
      `${modelCount} models, ${(uiBytes / 1024).toFixed(1)} KiB UI (split) + ` +
      `${(agentBytes / 1024).toFixed(1)} KiB Agent meta`,
  )
}

await main()
