/**
 * Export build-time provider data from the same-version pi packages.
 *
 * The UI output contains the bundled model catalog and immutable provider
 * metadata. The Agent output contains only immutable provider metadata, so
 * building a runtime provider snapshot does not load pi-catalog's models.json.
 *
 * Omits default/false/null fields to keep generated modules small; consumers
 * fill defaults while indexing the data.
 */
import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"
import { ModelRuntime } from "@earendil-works/pi-coding-agent"

type SlimModel = {
  id: string
  name?: string
  api?: string
  contextWindow?: number
  vision?: boolean
  inputCostPerMTok?: number
  outputCostPerMTok?: number
  reasoning?: boolean
  toolsUnsupported?: boolean
}

type SlimProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
  models: SlimModel[]
}

type SlimCatalog = {
  providerOrder: string[]
  providers: SlimProvider[]
}

type StaticProvider = Omit<SlimProvider, "models">

const GENERATED_HEADER = `/* eslint-disable */
/* Generated by export-bundled-catalog.ts. Do not edit. */

`

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v)
}

function slimModel(m: {
  id: string
  name?: string
  api?: string
  reasoning?: boolean
  input?: readonly string[]
  supportsTools?: boolean
  cost?: { input?: number; output?: number }
  contextWindow?: number | null
}): SlimModel {
  const out: SlimModel = { id: String(m.id) }
  const name = m.name != null ? String(m.name) : ""
  if (name && name !== out.id) out.name = name
  if (typeof m.api === "string" && m.api) out.api = m.api

  if (isFiniteNumber(m.contextWindow) && m.contextWindow > 0) {
    out.contextWindow = m.contextWindow
  }

  if (Array.isArray(m.input) && m.input.includes("image")) {
    out.vision = true
  }

  const costIn = m.cost?.input
  const costOut = m.cost?.output
  if (isFiniteNumber(costIn)) out.inputCostPerMTok = costIn
  if (isFiniteNumber(costOut)) out.outputCostPerMTok = costOut

  if (m.reasoning === true) out.reasoning = true
  if (m.supportsTools === false) out.toolsUnsupported = true
  return out
}

async function buildCatalog(): Promise<SlimCatalog> {
  const runtime = await ModelRuntime.create({ modelsPath: null })
  const providers = runtime.getProviders()
  const providerOrder = providers.map((provider) => provider.id)
  return {
    providerOrder,
    providers: providers.map((provider): SlimProvider => {
      const auth = provider.auth
      return {
        id: provider.id,
        supportsLogin: Boolean(auth.oauth || auth.apiKey?.login),
        models: provider.getModels().map((model) => slimModel(model)),
      }
    }),
  }
}

function renderUiCatalog(catalog: SlimCatalog): string {
  return `${GENERATED_HEADER}export type GeneratedCatalogModel = {
  id: string
  name?: string
  api?: string
  contextWindow?: number
  vision?: boolean
  inputCostPerMTok?: number
  outputCostPerMTok?: number
  reasoning?: boolean
  toolsUnsupported?: boolean
  priority?: number
}

export type GeneratedCatalogProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
  models: GeneratedCatalogModel[]
}

export type GeneratedBundledCatalog = {
  providerOrder: string[]
  providers: GeneratedCatalogProvider[]
}

export const bundledCatalog: GeneratedBundledCatalog = ${JSON.stringify(catalog)}
`
}

function renderAgentProviders(catalog: SlimCatalog): string {
  const providers: StaticProvider[] = catalog.providers.map(
    ({ id, supportsLogin, loginProviderId }) => {
      const provider: StaticProvider = { id }
      if (supportsLogin) provider.supportsLogin = true
      if (loginProviderId) provider.loginProviderId = loginProviderId
      return provider
    },
  )
  return `${GENERATED_HEADER}export type StaticProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
}

export const staticProviders: readonly StaticProvider[] = ${JSON.stringify(providers)}
`
}

function writeGenerated(outPath: string, contents: string): number {
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, contents, "utf8")
  return fs.statSync(outPath).size
}

async function main(): Promise<void> {
  const here = path.dirname(fileURLToPath(import.meta.url))
  const repoRoot = path.resolve(here, "../../..")
  const uiOutPath = path.join(
    repoRoot,
    "packages/vibefly-ui/src/generated/bundledCatalog.ts",
  )
  const agentOutPath = path.join(
    repoRoot,
    "packages/vibefly-agent/src/generated/providerCatalog.ts",
  )
  const catalog = await buildCatalog()
  const uiBytes = writeGenerated(uiOutPath, renderUiCatalog(catalog))
  const agentBytes = writeGenerated(agentOutPath, renderAgentProviders(catalog))
  const modelCount = catalog.providers.reduce((n, p) => n + p.models.length, 0)
  console.error(
    `export-bundled-catalog: ${catalog.providers.length} providers, ` +
      `${modelCount} models, ${(uiBytes / 1024).toFixed(1)} KiB UI + ` +
      `${(agentBytes / 1024).toFixed(1)} KiB Agent`,
  )
}

await main()
