/**
 * Export build-time provider data from the same-version Oh My Pi packages.
 *
 * The UI output contains the bundled model catalog and immutable provider
 * metadata. The Agent output contains only immutable provider metadata, so
 * building a runtime provider snapshot does not load pi-catalog's models.json.
 *
 * Omits default/false/null fields to keep generated modules small; consumers
 * fill defaults while indexing the data.
 */
import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"
import {
  getBundledModels,
  getBundledProviders,
  type GeneratedProvider,
} from "@oh-my-pi/pi-catalog/models"
import { buildModelProviderPriorityRank } from "@oh-my-pi/pi-catalog/identity"
import { getOAuthProviders } from "@oh-my-pi/pi-ai/oauth"

type SlimModel = {
  id: string
  name?: string
  api?: string
  contextWindow?: number
  vision?: boolean
  inputCostPerMTok?: number
  outputCostPerMTok?: number
  reasoning?: boolean
  toolsUnsupported?: boolean
  priority?: number
}

type SlimProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
  models: SlimModel[]
}

type SlimCatalog = {
  providerOrder: string[]
  providers: SlimProvider[]
}

type StaticProvider = Omit<SlimProvider, "models">

const GENERATED_HEADER = `/* eslint-disable */
/* Generated by export-bundled-catalog.ts. Do not edit. */

`

function isFiniteNumber(v: unknown): v is number {
  return typeof v === "number" && Number.isFinite(v)
}

function slimModel(m: {
  id: string
  name?: string
  api?: string
  reasoning?: boolean
  input?: readonly string[]
  supportsTools?: boolean
  cost?: { input?: number; output?: number }
  contextWindow?: number | null
  priority?: number
}): SlimModel {
  const out: SlimModel = { id: String(m.id) }
  const name = m.name != null ? String(m.name) : ""
  if (name && name !== out.id) out.name = name
  if (typeof m.api === "string" && m.api) out.api = m.api

  if (isFiniteNumber(m.contextWindow) && m.contextWindow > 0) {
    out.contextWindow = m.contextWindow
  }

  if (Array.isArray(m.input) && m.input.includes("image")) {
    out.vision = true
  }

  const costIn = m.cost?.input
  const costOut = m.cost?.output
  if (isFiniteNumber(costIn)) out.inputCostPerMTok = costIn
  if (isFiniteNumber(costOut)) out.outputCostPerMTok = costOut

  if (m.reasoning === true) out.reasoning = true
  if (m.supportsTools === false) out.toolsUnsupported = true
  if (isFiniteNumber(m.priority)) out.priority = m.priority

  return out
}

function buildCatalog(): SlimCatalog {
  const rank = buildModelProviderPriorityRank()
  const providerOrder = [...rank.entries()]
    .sort((a, b) => a[1] - b[1] || a[0].localeCompare(b[0]))
    .map(([id]) => id)

  const modelsByProvider = new Map<string, SlimModel[]>()
  for (const provider of getBundledProviders()) {
    const providerId = String(provider)
    let models: SlimModel[] = []
    try {
      const bundled = getBundledModels(provider as GeneratedProvider)
      models = bundled.map((m) => slimModel(m as Parameters<typeof slimModel>[0]))
    } catch {
      models = []
    }
    modelsByProvider.set(providerId, models)
  }

  const loginProviders = getOAuthProviders()
  const loginById = new Map(loginProviders.map((provider) => [provider.id, provider]))
  const providerIds = new Set([
    ...modelsByProvider.keys(),
    ...loginProviders.map((provider) => provider.id),
  ])
  const providers = [...providerIds]
    .sort((a, b) => a.localeCompare(b))
    .map((id): SlimProvider => {
      const directLogin = loginById.get(id)
      const mappedLogin = directLogin
        ? directLogin.id
        : loginProviders.find((provider) => provider.storeCredentialsAs === id)?.id
      const provider: SlimProvider = {
        id,
        models: modelsByProvider.get(id) ?? [],
      }
      if (mappedLogin) provider.supportsLogin = true
      if (mappedLogin && mappedLogin !== id) provider.loginProviderId = mappedLogin
      return provider
    })
  return { providerOrder, providers }
}

function renderUiCatalog(catalog: SlimCatalog): string {
  return `${GENERATED_HEADER}export type GeneratedCatalogModel = {
  id: string
  name?: string
  api?: string
  contextWindow?: number
  vision?: boolean
  inputCostPerMTok?: number
  outputCostPerMTok?: number
  reasoning?: boolean
  toolsUnsupported?: boolean
  priority?: number
}

export type GeneratedCatalogProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
  models: GeneratedCatalogModel[]
}

export type GeneratedBundledCatalog = {
  providerOrder: string[]
  providers: GeneratedCatalogProvider[]
}

export const bundledCatalog: GeneratedBundledCatalog = ${JSON.stringify(catalog)}
`
}

function renderAgentProviders(catalog: SlimCatalog): string {
  const providers: StaticProvider[] = catalog.providers.map(
    ({ id, supportsLogin, loginProviderId }) => {
      const provider: StaticProvider = { id }
      if (supportsLogin) provider.supportsLogin = true
      if (loginProviderId) provider.loginProviderId = loginProviderId
      return provider
    },
  )
  return `${GENERATED_HEADER}export type StaticProvider = {
  id: string
  supportsLogin?: boolean
  loginProviderId?: string
}

export const staticProviders: readonly StaticProvider[] = ${JSON.stringify(providers)}
`
}

function writeGenerated(outPath: string, contents: string): number {
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, contents, "utf8")
  return fs.statSync(outPath).size
}

function main(): void {
  const here = path.dirname(fileURLToPath(import.meta.url))
  const repoRoot = path.resolve(here, "../../..")
  const uiOutPath = path.join(
    repoRoot,
    "packages/vibefly-ui/src/generated/bundledCatalog.ts",
  )
  const agentOutPath = path.join(
    repoRoot,
    "packages/vibefly-agent/src/generated/providerCatalog.ts",
  )
  const catalog = buildCatalog()
  const uiBytes = writeGenerated(uiOutPath, renderUiCatalog(catalog))
  const agentBytes = writeGenerated(agentOutPath, renderAgentProviders(catalog))
  const modelCount = catalog.providers.reduce((n, p) => n + p.models.length, 0)
  console.error(
    `export-bundled-catalog: ${catalog.providers.length} providers, ` +
      `${modelCount} models, ${(uiBytes / 1024).toFixed(1)} KiB UI + ` +
      `${(agentBytes / 1024).toFixed(1)} KiB Agent`,
  )
}

main()
