packages:
  - "packages/vibefly-simplerpc/typeScript"
  - "packages/vibefly-simplerpc/typeScript-node"
  - "packages/vibefly-uiagent-shared"
  - "packages/vibefly-agent"
  - "packages/vibefly-ui"
allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
