packages:
  - "packages/vibefly-simplerpc/typeScript"
  - "packages/vibefly-simplerpc/typeScript-node"
  - "packages/vibefly-uiagent-shared"
  - "packages/vibefly-agent"
  - "packages/vibefly-ui"
allowBuilds:
  '@google/genai': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
